### ISSUE TITLE
ValueError: low >= high

### ISSUE THREAD

**Issue by enhuiz** [ivanvovk/WaveGrad#10] opened 2020-10-29 14:31 UTC
https://github.com/ivanvovk/WaveGrad/blob/6be2f4c228e366eb850db5983344508c0d0fac87/data.py#L47-L49

Since `np.random.randint` has the right exclusive boundary, np.random.randint(0, 0) raises an error. Consider to switch to `random.randint` or change to `audio.shape[-1] > self.segment_length`?

**Comment by ivanvovk** [comment] 2020-10-29 15:33
@enhuiz Yeah, you are right, it is a bug. Thank you for your feedback. I will push an update with second approach.

**Comment by ivanvovk** [comment] 2020-11-01 13:29
Closing issue since the problem is solved.

**Closed by ivanvovk** 2020-11-01 13:29 UTC
Labels: update
